remote_theme: just-the-docs/just-the-docs
color_scheme: liwazi
search_enabled: false
title: liwazi Lab
logo: https://www.cam.ac.uk/sites/www.cam.ac.uk/themes/fresh/images/interface/cambridge_university2.svg
