remote_theme: just-the-docs/just-the-docs
color_scheme: liwazi
search_enabled: true
title: liwazi Lab
logo: https://www.lib.cam.ac.uk/sites/all/themes/cambridge_theme/images/interface/main-logo-small.png
